# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 11"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: ""
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "assets/fonts/*"
    - "!assets/{img,js,scss,css}/**/*"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "assets/js/admin-mesh-notifications.js"
    - "assets/js/mesh.js"
    - "assets/js/admin-mesh.js"

LOCAL_PATH: "http://mesh.local"
